---
title: "Flic's Farewell: 2.5 year Wallace Lab Summary"
author: "Flic Anderson"
date: "16/12/2021"
output: 
  ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>

<script>
    $(document).ready(function() {
      $('slide:not(.title-slide, .backdrop, .segue)').append('<footer label=\"bit.ly/riboviz-new-users"></footer>');    
    })
</script>

<style>
  footer:after {
    content: attr(label);
    font-size: 12pt;
    position: absolute;
    bottom: 20px;
    left: 700px;
    line-height: 1.9;
  }
</style>

<style type="text/css">
slides > slide:not(.nobackground):after {
  content: '';
}
</style>

<div class="notes">

Bio: 

Flic Anderson has been a Research Assistant in Bioinformatics in the Wallace Lab (within the Institute for Cell Biology) at the University of Edinburgh (July 2019 - December 2021). The Wallace Lab works to understand how translation works within cells (particularly of fungi) and what factors control and regulate protein synthesis. 

Flic is part of the development team for the 'riboviz' open source software package for processing and analysis of ribosome profiling data, working with colleagues from EPCC (University of Edinburgh) to make the codebase more robust & sustainable.   

With a background in Ecology and Botany (previously a Research Assistant at the Royal Botanic Garden Edinburgh), Flic has worked with a wide range of types of biological data using different software tools and programming languages (particularly R) for the last 8 years, and found herself drawn towards bioinformatics and research software engineering. 

Flic is a member of the Edinburgh Carpentries and a certified Carpentries instructor in foundational coding and data science skills for researchers. 


Title: Flic's Farewell: A Wallace Lab Summary


Abstract:  

Explaining how new users can get started with 'riboviz' open source software package for processing and analysing ribosome profiling (RNA sequence) data.

</div>



## Outline: 

* What I've done
* Outputs 
* Obstacles 
* What I've learned 
* What I'd do differently 
* Highlights 



## Projects I've worked on

Riboviz: *developing open source ribosome profiling software*   

*  mostly this!

Ed-DaSH: *data science training for health and biosciences*   

 * helping develop Nextflow training materials and other workshop hackathons   
 * assisting delivery of workshops  

4273pi: *delivering bioinformatics lesson content in Scottish schools*  

* assisted in online workshops delivering CPD/training to teachers

 *+ involved with local data/software/library Carpentries group*



## Outputs: published 

Contributed to papers/articles: 

* Bioinformatics - manuscript with editors, awaiting decision:  
  - *"riboviz 2: A flexible and robust ribosome profiling data analysis and visualization workflow"* [preprint: 10.1101/2021.05.14.443910](https://doi.org/10.1101/2021.05.14.443910)
 
* Biochemist article published:  
  - *"The benefits of an open-science approach in student research projects"* [DOI: 10.1042/bio_2021_198](https://doi.org/10.1042/bio_2021_198)
  
* PLOS Computational Biology - manuscript accepted: 
  - *"Bringing bioinformatics to schools with the 4273pi project"*



## Outputs: supervising 

Co-supervised 4 students on riboviz projects: 

*Undergraduate:*  

* Anna Kurowska  
* Emma MacKenzie  
* Sophie Winterbourne  

*Masters:* 

* Siyin Xue



## Outputs: presenting

Poster:   

* RNA 2021 (riboviz 2 - prize-winning!) 


External Talks:   

* EdinbR "connecting Rmarkdown, Shiny and Nextflow": [Watch on EdinbR YouTube Channel](https://youtu.be/2C_WpraLznc?t=1596) 

Lab & Project Meetings:  
(Thank you all for listening about riboviz!)




## Outputs: teaching/instructing

Carpentries Teaching: 

- Instructor: Data Carpentry for Genomics, Command Line & R   
- Helper: Command Line, Conda, Nextflow  
- Host: Scottish Funding Council Data Carpentry workshop: R, Regular Expressions, SQL  

Workshops:  

- Wallace Lab git workshop  
- Ed-DaSH git, github & collaborative working  
- Biochemical Society - Ribosome Profiling Workshop



## Obstacles

* getting a (working) laptop 
* vertigo 
* pandemic & lockdowns  
* anxiety 
* remote teaching / supervision



## What I've learned  

* Real experience of bioinformatics  
* Teaching/instructing software engineering & bioinformatics skills  
* R markdown / html presentations (such as this) :D   
* I'm more of a software/data engineer than a bioinformatician (ie more informatics than bio)  
* PhD choice!    
* Guided my career path: somewhere between software and researchers!



## What I'd do differently  

* less global pandemics / health issues   
* learn python earlier in the project to review Mike's PRs better & contribute to .py codebase    
* be more Mike Jackson generally (see: WWMJD)  
* offer more user interviews/user sessions/demos earlier  
* understand how I learn (pair-programming / hackathon / pseudo-code to understand code problems etc)  
* block out more preparation time ahead of workshops/presentations - know my 'process'    
* get a mac? (Start with non-dual-booted linux on a laptop if nothing else...)



## Highlights 

* being **part of a team** on a research software development project
* **learning better practices** in software development 
* **training others** in software tools & techniques 
* finding out about **what helps/hinders new users** & researchers
* being part of a GREAT LAB of amazing and inspiring scientists!

 -> starting PhD Jan 10th 2022 at EPCC:  
     *What aspects of Research Software projects generate effective & successful software?*  
  tools, techniques, teaching & environmental factors



## Thanks 

You've all been wonderful! 

Thanks Wallace Lab! 

<3